/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.kubesure.aggregate.datatypes;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Holds lists of prospect companies */
@org.apache.avro.specific.AvroGenerated
public class AggregatedProspectCompany extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1047955881611105388L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AggregatedProspectCompany\",\"namespace\":\"io.kubesure.aggregate.datatypes\",\"doc\":\"Holds lists of prospect companies\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"companies\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"ProspectCompany\",\"doc\":\"Prospect company with registered prospect as shareholders\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"companyName\",\"type\":\"string\"},{\"name\":\"tradeLicenseNumber\",\"type\":\"string\"},{\"name\":\"match\",\"type\":\"boolean\"},{\"name\":\"eventTime\",\"type\":\"long\",\"logicalType\":\"local-timestamp-millis\"},{\"name\":\"shareHolders\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Prospect\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"cif\",\"type\":\"string\"},{\"name\":\"account\",\"type\":\"string\"},{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"lastName\",\"type\":\"string\"},{\"name\":\"fullName\",\"type\":\"string\"},{\"name\":\"match\",\"type\":\"boolean\"}]}}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AggregatedProspectCompany> ENCODER =
      new BinaryMessageEncoder<AggregatedProspectCompany>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AggregatedProspectCompany> DECODER =
      new BinaryMessageDecoder<AggregatedProspectCompany>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AggregatedProspectCompany> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AggregatedProspectCompany> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AggregatedProspectCompany> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AggregatedProspectCompany>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AggregatedProspectCompany to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AggregatedProspectCompany from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AggregatedProspectCompany instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AggregatedProspectCompany fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long id;
   private java.util.List<io.kubesure.aggregate.datatypes.ProspectCompany> companies;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AggregatedProspectCompany() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param companies The new value for companies
   */
  public AggregatedProspectCompany(java.lang.Long id, java.util.List<io.kubesure.aggregate.datatypes.ProspectCompany> companies) {
    this.id = id;
    this.companies = companies;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return companies;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: companies = (java.util.List<io.kubesure.aggregate.datatypes.ProspectCompany>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'companies' field.
   * @return The value of the 'companies' field.
   */
  public java.util.List<io.kubesure.aggregate.datatypes.ProspectCompany> getCompanies() {
    return companies;
  }


  /**
   * Sets the value of the 'companies' field.
   * @param value the value to set.
   */
  public void setCompanies(java.util.List<io.kubesure.aggregate.datatypes.ProspectCompany> value) {
    this.companies = value;
  }

  /**
   * Creates a new AggregatedProspectCompany RecordBuilder.
   * @return A new AggregatedProspectCompany RecordBuilder
   */
  public static io.kubesure.aggregate.datatypes.AggregatedProspectCompany.Builder newBuilder() {
    return new io.kubesure.aggregate.datatypes.AggregatedProspectCompany.Builder();
  }

  /**
   * Creates a new AggregatedProspectCompany RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AggregatedProspectCompany RecordBuilder
   */
  public static io.kubesure.aggregate.datatypes.AggregatedProspectCompany.Builder newBuilder(io.kubesure.aggregate.datatypes.AggregatedProspectCompany.Builder other) {
    if (other == null) {
      return new io.kubesure.aggregate.datatypes.AggregatedProspectCompany.Builder();
    } else {
      return new io.kubesure.aggregate.datatypes.AggregatedProspectCompany.Builder(other);
    }
  }

  /**
   * Creates a new AggregatedProspectCompany RecordBuilder by copying an existing AggregatedProspectCompany instance.
   * @param other The existing instance to copy.
   * @return A new AggregatedProspectCompany RecordBuilder
   */
  public static io.kubesure.aggregate.datatypes.AggregatedProspectCompany.Builder newBuilder(io.kubesure.aggregate.datatypes.AggregatedProspectCompany other) {
    if (other == null) {
      return new io.kubesure.aggregate.datatypes.AggregatedProspectCompany.Builder();
    } else {
      return new io.kubesure.aggregate.datatypes.AggregatedProspectCompany.Builder(other);
    }
  }

  /**
   * RecordBuilder for AggregatedProspectCompany instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AggregatedProspectCompany>
    implements org.apache.avro.data.RecordBuilder<AggregatedProspectCompany> {

    private long id;
    private java.util.List<io.kubesure.aggregate.datatypes.ProspectCompany> companies;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.kubesure.aggregate.datatypes.AggregatedProspectCompany.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.companies)) {
        this.companies = data().deepCopy(fields()[1].schema(), other.companies);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing AggregatedProspectCompany instance
     * @param other The existing instance to copy.
     */
    private Builder(io.kubesure.aggregate.datatypes.AggregatedProspectCompany other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.companies)) {
        this.companies = data().deepCopy(fields()[1].schema(), other.companies);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public io.kubesure.aggregate.datatypes.AggregatedProspectCompany.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public io.kubesure.aggregate.datatypes.AggregatedProspectCompany.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'companies' field.
      * @return The value.
      */
    public java.util.List<io.kubesure.aggregate.datatypes.ProspectCompany> getCompanies() {
      return companies;
    }


    /**
      * Sets the value of the 'companies' field.
      * @param value The value of 'companies'.
      * @return This builder.
      */
    public io.kubesure.aggregate.datatypes.AggregatedProspectCompany.Builder setCompanies(java.util.List<io.kubesure.aggregate.datatypes.ProspectCompany> value) {
      validate(fields()[1], value);
      this.companies = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'companies' field has been set.
      * @return True if the 'companies' field has been set, false otherwise.
      */
    public boolean hasCompanies() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'companies' field.
      * @return This builder.
      */
    public io.kubesure.aggregate.datatypes.AggregatedProspectCompany.Builder clearCompanies() {
      companies = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AggregatedProspectCompany build() {
      try {
        AggregatedProspectCompany record = new AggregatedProspectCompany();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.companies = fieldSetFlags()[1] ? this.companies : (java.util.List<io.kubesure.aggregate.datatypes.ProspectCompany>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AggregatedProspectCompany>
    WRITER$ = (org.apache.avro.io.DatumWriter<AggregatedProspectCompany>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AggregatedProspectCompany>
    READER$ = (org.apache.avro.io.DatumReader<AggregatedProspectCompany>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    long size0 = this.companies.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (io.kubesure.aggregate.datatypes.ProspectCompany e0: this.companies) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      long size0 = in.readArrayStart();
      java.util.List<io.kubesure.aggregate.datatypes.ProspectCompany> a0 = this.companies;
      if (a0 == null) {
        a0 = new SpecificData.Array<io.kubesure.aggregate.datatypes.ProspectCompany>((int)size0, SCHEMA$.getField("companies").schema());
        this.companies = a0;
      } else a0.clear();
      SpecificData.Array<io.kubesure.aggregate.datatypes.ProspectCompany> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<io.kubesure.aggregate.datatypes.ProspectCompany>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          io.kubesure.aggregate.datatypes.ProspectCompany e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new io.kubesure.aggregate.datatypes.ProspectCompany();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<io.kubesure.aggregate.datatypes.ProspectCompany> a0 = this.companies;
          if (a0 == null) {
            a0 = new SpecificData.Array<io.kubesure.aggregate.datatypes.ProspectCompany>((int)size0, SCHEMA$.getField("companies").schema());
            this.companies = a0;
          } else a0.clear();
          SpecificData.Array<io.kubesure.aggregate.datatypes.ProspectCompany> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<io.kubesure.aggregate.datatypes.ProspectCompany>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              io.kubesure.aggregate.datatypes.ProspectCompany e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new io.kubesure.aggregate.datatypes.ProspectCompany();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










